export const SELECT_DEVICE = 'SELECT_DEVICE'
export const GET_DEVICES = 'GET_DEVICES'
export const GET_DEVICE_STATUS = 'GET_DEVICE_STATUS'
export const GET_DEVICE_COMMAND_HISTORY = 'GET_DEVICE_COMMAND_HISTORY'
export const SET_LOADING = 'LOADING'
export const SET_IDLE = 'IDLE'
export const CLEAR_CHOSEN_DEVICE = 'CLEAR_CHOSEN_DEVICE'
export const GET_FULL_DEVICE_INFO = 'GET_FULL_DEVICE_INFO'
export const SET_CHOSEN_DEVICE_ID = 'SET_CHOSEN_DEVICE_ID'
export const SEND_COMMAND = 'SEND_COMMAND'
export const GET_TYPES = 'GET_TYPES'



